"""создани моделей

Revision ID: 01da87062b8b
Revises: 60d72167c6d3
Create Date: 2026-04-14 11:12:46.478526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01da87062b8b'
down_revision: Union[str, Sequence[str], None] = '60d72167c6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    application_status = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus')
    application_status.create(op.get_bind())

    topic_status = postgresql.ENUM('OPEN', 'CLOSED', 'ASSIGNED', name='topicstatus')
    topic_status.create(op.get_bind())

    user_role = postgresql.ENUM('STUDENT', 'TEACHER', 'ADMIN', name='userrole')
    user_role.create(op.get_bind())

    op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('applications', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'),
                    existing_nullable=False,
                    postgresql_using="status::applicationstatus")
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('saved_topics', 'id')
    op.drop_column('saved_topics', 'created_at')
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('teachers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('teachers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('topic_skills', 'id')
    op.add_column('topics', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('topics', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OPEN', 'CLOSED', 'ASSIGNED', name='topicstatus'),
               existing_nullable=False,
                postgresql_using="status::topicstatus")
    op.add_column('user_skills', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user_skills', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'),
               existing_nullable=False,
               postgresql_using="role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('user_skills', 'updated_at')
    op.drop_column('user_skills', 'created_at')
    op.alter_column('topics', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'ASSIGNED', name='topicstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('topics', 'updated_at')
    op.drop_column('topics', 'created_at')
    op.add_column('topic_skills', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'updated_at')
    op.drop_column('teachers', 'created_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('skills', 'updated_at')
    op.add_column('saved_topics', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('saved_topics', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('departments', 'updated_at')
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('applications', 'updated_at')
    postgresql.ENUM(name='applicationstatus').drop(op.get_bind())
    postgresql.ENUM(name='topicstatus').drop(op.get_bind())
    postgresql.ENUM(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
