"""email

Revision ID: 5e91468642e9
Revises: a28056b7fd35
Create Date: 2026-04-20 15:28:58.552351

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '5e91468642e9'
down_revision: Union[str, Sequence[str], None] = 'a28056b7fd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
