"""reset_migrations

Revision ID: a4382fcd0415
Revises: a28056b7fd35
Create Date: 2026-04-27 12:14:39.846456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4382fcd0415'
down_revision: Union[str, Sequence[str], None] = 'a28056b7fd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'role',
            postgresql.ENUM('STUDENT', 'TEACHER', 'ADMIN', name='userrole'),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
